### ISSUE TITLE
Displaying strings and numbers doesn't work

### ISSUE THREAD

**Issue by db2u1980** [microbit-makecode-packages/OLED12864_I2C#1]
Added package, demo doesn't fully work.   I can draw pixels and rectangles, but not display any text or numbers.   Is there an additional package that is a dependency for this to work?

**Comment by shaoziyang** [comment]
This package is work fine with microbit and 0.96 inch OLED. You may try my demo, I using [makecode online environment ](https://makecode.microbit.org/)to create it.  

[test.zip](https://github.com/microbit-makecode-packages/OLED12864_I2C/files/2044688/test.zip)

What type of **OLED** module do you use? This package support 128x64 OLED now, other resolution will be support late.

**Comment by db2u1980** [comment]
Oh, my mistake, I thought my oled was 128x64 but turns out it is 64x48:
https://www.sparkfun.com/products/14532

**Comment by shaoziyang** [comment]
The paramters in package need be modify for 64x48 resolution. I will upgrade the package to support more resolution.

**Comment by wallacekst** [comment]
I also had the same problem. I am using Makecode but, after they updated the web-based environment recently, it keeps telling me that I have compilation error when I used  "show number" or "show string". The OLED package originally worked for the old Makecode environment.

**Comment by shaoziyang** [comment]
I will check the problem and update it.

**Comment by shaoziyang** [comment]
This issue is cause by makecode v1 increase firmware size, and not enough flash rom to run the OLED package. I will try to reduce the package.

**Comment by wallacekst** [comment]
looking forward ....

**Comment by shaoziyang** [comment]
@db2u1980 @wallacekst Extension working now.
